"""Generate a URDF (for robot_state_publisher / RViz) from the MuJoCo model.

    python3 -m h1_rl.urdf            # rewrites models/h1/h1.urdf

The kinematic tree, joint axes/limits, inertias and visual meshes are taken
from models/h1/h1.xml, so RViz shows exactly the robot that is simulated.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from xml.dom import minidom
from xml.etree import ElementTree as ET

import mujoco
import numpy as np

from .config import load_config, model_dir
from .robot import RobotSpec, build_model

PACKAGE_URI = "package://h1_rl/models/h1/meshes"
VELOCITY_LIMITS = {"hip": 23.0, "knee": 14.0, "ankle": 9.0, "torso": 23.0, "shoulder": 9.0, "elbow": 20.0}


def quat_to_rpy(q) -> tuple[float, float, float]:
    w, x, y, z = q
    roll = np.arctan2(2 * (w * x + y * z), 1 - 2 * (x * x + y * y))
    pitch = np.arcsin(np.clip(2 * (w * y - z * x), -1.0, 1.0))
    yaw = np.arctan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))
    return float(roll), float(pitch), float(yaw)


def fmt(v) -> str:
    return " ".join(f"{float(x):.6g}" for x in v)


def build_urdf(cfg: dict) -> str:
    model = build_model(cfg, visual=True)
    robot = RobotSpec.from_config(cfg)
    spec = mujoco.MjSpec.from_file(str(model_dir() / "h1.xml"))
    meshes_by_body: dict[str, list[tuple[str, str]]] = {}
    for g in spec.geoms:
        if g.type == mujoco.mjtGeom.mjGEOM_MESH and g.contype == 0 and g.conaffinity == 0:
            body = g.parent.name
            meshes_by_body.setdefault(body, []).append((g.meshname, g.material or "black"))

    root = ET.Element("robot", name="h1")
    for name, rgba in (("black", "0.15 0.15 0.15 1"), ("white", "0.9 0.9 0.9 1")):
        ET.SubElement(ET.SubElement(root, "material", name=name), "color", rgba=rgba)

    for b in range(1, model.nbody):
        bname = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, b)
        link = ET.SubElement(root, "link", name=bname)
        inertial = ET.SubElement(link, "inertial")
        ET.SubElement(inertial, "origin", xyz=fmt(model.body_ipos[b]), rpy=fmt(quat_to_rpy(model.body_iquat[b])))
        ET.SubElement(inertial, "mass", value=f"{model.body_mass[b]:.6g}")
        ixx, iyy, izz = model.body_inertia[b]
        ET.SubElement(inertial, "inertia", ixx=f"{ixx:.6g}", ixy="0", ixz="0", iyy=f"{iyy:.6g}", iyz="0",
                      izz=f"{izz:.6g}")
        for mesh, material in meshes_by_body.get(bname, []):
            visual = ET.SubElement(link, "visual")
            ET.SubElement(visual, "origin", xyz="0 0 0", rpy="0 0 0")
            ET.SubElement(ET.SubElement(visual, "geometry"), "mesh", filename=f"{PACKAGE_URI}/{mesh}.stl")
            ET.SubElement(visual, "material", name=material)

        parent = model.body_parentid[b]
        if parent == 0:
            continue  # pelvis: floating base, pose comes from TF (odom -> pelvis)
        jid = model.body_jntadr[b]
        jname = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, jid)
        joint = ET.SubElement(root, "joint", name=jname, type="revolute")
        ET.SubElement(joint, "origin", xyz=fmt(model.body_pos[b]), rpy=fmt(quat_to_rpy(model.body_quat[b])))
        ET.SubElement(joint, "parent", link=mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, parent))
        ET.SubElement(joint, "child", link=bname)
        ET.SubElement(joint, "axis", xyz=fmt(model.jnt_axis[jid]))
        k = robot.joint_names.index(jname)
        vel = next(v for key, v in VELOCITY_LIMITS.items() if key in jname)
        lo, hi = model.jnt_range[jid]
        ET.SubElement(joint, "limit", lower=f"{lo:.4g}", upper=f"{hi:.4g}",
                      effort=f"{robot.torque_limit[k]:.4g}", velocity=f"{vel:.4g}")

    xml = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    header = ("<?xml version=\"1.0\"?>\n<!-- Generated by `python3 -m h1_rl.urdf` from models/h1/h1.xml. "
              "Unitree H1 description (BSD-3-Clause, Unitree Robotics). -->\n")
    return header + xml.split("\n", 1)[1]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output", default=None)
    args = ap.parse_args()
    out = Path(args.output) if args.output else model_dir() / "h1.urdf"
    out.write_text(build_urdf(load_config()), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
